### ISSUE TITLE
No an issue

### ISSUE THREAD

**Issue by yahoo2016** [mazsi-on-xtrx/xtrx-system-test#1]
Nice work and very useful.  Xilinx PCIe DMA core could be used instead of the PCIe core. I'll try Xilinx PCIe DMA core with Xilinx Linux driver/test software when I have time.

**Comment by mazsi-on-xtrx** [comment]
certainly!
we are playing and experimenting with a DMA-less architecture on purpose, but the vendor's PCIe DMA IP core should work just as well.
